name: .NET Linux Test

on:
  pull_request:
    branches: [ "**" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Nerdbank.GitVersioning to set version variables
      uses: dotnet/nbgv@master
      id: nbgv

    - name: Restore dependencies
      run: dotnet restore ProgressTracking.sln

    - name: Build
      run: dotnet build --no-restore --configuration Release ProgressTracking.sln

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release ProgressTracking.sln