name: .NET Linux Publish Release

on:
  release:
    types: [ "published" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Restore dependencies
      run: dotnet restore ProgressTracking.sln

    - name: Build
      run: dotnet build --no-restore --configuration Release ProgressTracking.sln -p:PublicRelease=true

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release ProgressTracking.sln

    - name: Publish Nuget to nuget.org
      run: dotnet nuget push **/*.nupkg -k ${NUGET_PUSH_API_KEY} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols 
      env:
        NUGET_PUSH_API_KEY: ${{ secrets.NUGET_PUSH_API_KEY }}
