name: .NET Linux Publish Pre-Release

on:
  push:
    branches: [ "main", "v*" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Restore dependencies
      run: dotnet restore ProgressTracking.sln

    - name: Build
      run: dotnet build --no-restore --configuration Release ProgressTracking.sln

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release ProgressTracking.sln
      
    - name: Publish NuGet package to GitHub
      run: dotnet nuget push **/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/jetelain/index.json --skip-duplicate
